---
# Defines tasks to install and configure NTP

- name: Include the OS specific varibles
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - common
    - ntp

- name: Install NTP for Debian derivatives
  apt: >
    pkg={{ item }}
    update_cache=yes
    state=latest
  with_items: ntp_packages
  when: ansible_os_family == 'Debian'
  tags:
    - common
    - ntp

- name: Ensure NTP configuration directory
  file: >
    path={{ ntp_config_dir }}
    mode=0755 owner=root group=root
    state=directory
  tags:
    - common
    - ntp

- name: Write NTP configuration templates
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    mode=0644 owner=root group=root
    backup=yes
  with_items:
      - { src: 'ntp-conf.j2',
          dest: '{{ ntp_config_dir }}/ntp.conf' }
  notify:
    - restart ntp
  tags:
    - common
    - ntp

- name: Start NTP on server boot
  service: >
    name={{ ntp_service }}
    state=started
    enabled=yes
  tags:
    - common
    - ntp
